#!/bin/bash -l
#SBATCH --job-name=nm_mrifield
#SBATCH --gres=gpu:a40:1
#SBATCH --time=04:00:00
#SBATCH --output=log_%x

source .venv/bin/activate
export PYTHONPATH=$(pwd)/magnet-pinn:$PYTHONPATH
python3.11 mrifield/preprocessing/normalization.py
deactivate
