#!/bin/bash -l
#SBATCH --job-name=nm_mrifield
#SBATCH --gres=gpu:a40:1
#SBATCH --time=04:00:00
#SBATCH --output=/home/hpc/b190cb/b190cb19/ma_bohn/log

source /home/hpc/b190cb/b190cb19/ma_bohn/.venv/bin/activate
export PYTHONPATH=$(pwd)/magnet-pinn:$PYTHONPATH
python3.11 mrifield/preprocessing/normalization.py
deactivate
