#!/bin/bash -l
#SBATCH --job-name=pl_mrifield
#SBATCH --gres=gpu:a100:1
#SBATCH --time=00:20:00
#SBATCH --output=log_%x

source .venv/bin/activate
export PYTHONPATH=$(pwd)/magnet-pinn:$PYTHONPATH
export PYTHONPATH=$(pwd)/neuraloperator:$PYTHONPATH
python3.11 -m mrifield.train.plots
deactivate
