#!/bin/bash -l
#SBATCH --job-name=pl_mrifield
#SBATCH --gres=gpu:a100:1
#SBATCH --time=00:20:00
#SBATCH --output=/home/hpc/b190cb/b190cb19/ma_bohn/log_pl

source /home/hpc/b190cb/b190cb19/ma_bohn/.venv/bin/activate
export PYTHONPATH=$(pwd)/magnet-pinn:$PYTHONPATH
export PYTHONPATH=$(pwd)/neuraloperator:$PYTHONPATH
python3.11 -m mrifield.train.plots
deactivate
