#!/bin/bash -l
#SBATCH --job-name=tr_mrifield
#SBATCH --gres=gpu:a100:1
#SBATCH --time=24:00:00
#SBATCH --output=log_%x

source .venv/bin/activate
export PYTHONPATH=$(pwd)/mrifield/train:$PYTHONPATH
export PYTHONPATH=$(pwd)/magnet-pinn:$PYTHONPATH
export PYTHONPATH=$(pwd)/neuraloperator:$PYTHONPATH
python3.11 -m mrifield.train.train
deactivate
